name: Build and Test Docker Container

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t hello-world-html .

      - name: Run container for testing
        run: |
          docker run -d -p 8080:80 --name hello hello-world-html
          sleep 5
          curl -I http://localhost:8080 | grep "200 OK"

      - name: Stop and remove container
        run: |
          docker stop hello
          docker rm hello
